data:
  cutoff: 0.75
  dirname: "data"
  download: False
  interpolate: False
  visualise: False
model:
  early_stop: 10 #False, int
  name: "CustomCNN2"
  params:
    batch: 64
    lr: 0.00001
    decay: 0.000005
    epochs: 500
  target: "Abd-A" #Abd-A, Abd-B, Ubx
  type: "deep"
pipeline:
  cv: 5
  split: 
    test: 0.2
random_state: 2
verbose: True