data:
  dirname: "data"
  download: False
  visualise: False
  cutoff: 0.75
  interpolate: True
model:
  target: "Abd-A" #Abd-A, Abd-B, Ubx
  type: "deep"
  name: "Custom" #Custom
  params:
    batch: 32
pipeline:
  cv: 5
  split:
    test: 0.2
verbose: True