data:
  cutoff: 0.75
  dirname: "data"
  download: False
  interpolate: False
  visualise: False
model:
  early_stop: 10 #False, int
  layers: [20, 10]
  name: "CustomDNN1"
  params:
    batch: 16
    lr: 0.00005
    decay: 0.0001
    epochs: 1000
  target: "Abd-A" #Abd-A, Abd-B, Ubx
  type: "deep"
pipeline:
  cv: 5
  split:
    test: 0.2
random_state: 2
verbose: True